#!/bin/bash

# runit needs to be running before chef-server-ctl reconfigure in docker
# runit is not already running https://github.com/chef/chef-server/issues/62
export PATH=/opt/opscode/bin:/opt/opscode/bin/embedded:$PATH
/opt/opscode/embedded/bin/runsvdir-start &

# Get chef configuration ready
ln -s /opt/docker/chef-server.rb /etc/opscode

# reconfigure insists on being able to touch the certs for perms so we
# copy them to a place where it can. Getting the smell right kind of breaks
# cert rotation, but you know how opinionated chef can be on its stack...
cp -a /var/local/certs/..data/ /etc/opscode/certs

# Deal with touching bootstrapped
# chef-server-ctl reconfigure

while true; do
  chef-server-ctl tail -f || echo "No logs?!?"
  sleep 20
done

