#!/bin/bash -x

# runit needs to be running before chef-server-ctl reconfigure in docker
# runit is not already running https://github.com/chef/chef-server/issues/62
export PATH=/opt/cinc-server/bin:/opt/cinc-server/bin/embedded:$PATH
/opt/cinc-project/embedded/bin/runsvdir-start &


# Get chef configuration ready
ln -sf /opt/docker/cinc-server.rb /etc/cinc-project

# reconfigure insists on being able to touch the certs for perms so we
# copy them to a place where it can. Getting the smell right kind of breaks
# cert rotation, but you know how opinionated chef can be on its stack...
cp -a /var/local/certs/..data/ /etc/cinc-project/certs

/opt/docker/load_keys $NAMESPACE $BACKEND_KEYS
if [ $? -eq 0 ]; then # Not the first
  # touch boostrap
  cinc-server-ctl reconfigure
else # We are the first
  cinc-server-ctl reconfigure
  /opt/docker/save_keys $NAMESPACE $BACKEND_KEYS
fi

while true; do # show the chef server logs in an endlees loop
  chef-server-ctl tail -f || echo "No logs?!?"
  sleep 20
done

