#!/opt/opscode/embedded/bin/ruby
require 'k8s-client'

FILES={
  pivotal: '/etc/opscode/pivotal.pem',
  private_chef_secrets: '/etc/opscode/private-chef-secrets.json',
}

def build_secret(ns, name, keys)
  K8s::Resource.new(
    apiVersion: 'v1',
    kind: 'Secret',
    metadata: { namespace: ns, name: name, },
    data: keys )

end

def read_file(filename)
  Base64.encode64(File.read filename)
end

begin
  client = K8s::Client.in_cluster_config
  secrets = FILES.map {|key, file| [key, read_file(file)] }.to_h
  seq_req = build_secret(ARGV[0], ARGV[1], secrets)
  client.api('v1').resource('secrets', namespace: ARGV[0]).create_resource(seq_req)
end
